### ISSUE TITLE
Add an "instant" transition to curtain

### ISSUE THREAD

**Issue by StraToN** [godot-escoria/escoria-issues#102]
**Is your feature request related to a problem? Please describe.**
We have some transitions in the curtain already, but no "instant" transition. Let's add this.

**Describe the solution you'd like**
Just add a new "instant" transition to the curtain.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by balloonpopper** [comment]
I've tested the issue-102 branch code. Generally instant transitions work well. The things I discovered
* There's a very short period (2-3 frames) where the screen seems to black out between showing the original screen and the new screen. It's just long enough to cause the transition to feel "not right" - it's bearable as is, but ideally I'd prefer it was fixed. 

* When starting on room 12 with instant transition as the default, the full screen is drawn for a frame or two then blanks out and the transition in runs. This also occurs if you go from room 13 to room 12. This is happening because both the default and manual transition (as configured in room12.esc) are running.
* To prove this I set the default transition set to "curtain" - you get the curtain in transition running twice when you start room 12 directly

* If I set the default transition to curtain and change room 12's script so that the manual transition is "instant" i.e.
```
:ready
transition instant in
```
If you go from room 11 to room 12, room 12 never draws. The error on changing rooms is
```
 2022-3-31T22145 (W)	Warnings in file ESCObjectManager:unregister_object()
Unable to unregister object.
Object with global ID r12_l_exit room (room12, 5536) not found. If this was
part of a 'forced' registration, ignore this warning.
```
Moving the mouse shows that collision boxes are being processed in the debug window. Debug indicates the player is walking around.  If you can find the right spot to click you can transition back to room 11.  When you click the doorway it temporarily draws room 12 with a transition out then goes to room 11.
* Setting the default to instant and the room's ready transition in to "instant" still has the same effect (black screen but the game still running)

* Running a room directly seems to work fine.
* Instant transitions between rooms without manual transition commands works fine.
