### ISSUE TITLE
Selecting an ESCItem in the Godot GUI displays "Cannot get class 'ESCAnimationResource'" errors.

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#118]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
Select an ESCItem from the node tree while editing a level. 8 x "Cannot get class 'ESCAnimationResource'" errors appear in the output window.

**To Reproduce**
Select an ESCItem from the node tree while editing a level.

**Expected behavior**
No errors should appear

**Versions**
* Escoria: Develop branch
* Godot: 3.4.2

**Comment by dploeger** [comment]
This is a known issue and is due to Godot 3's missing support of custom resources. We hope to have this fixed in Godot 4.

Regardless, I just created #119, because that is what we're ultimately aiming for.

As this is out of Escoria's control and the error message doesn't restrict working with it, I'm closing this.
