### ISSUE TITLE
Right clicking during transition-in breaks

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#275]
**Describe the bug**

**Requires curtain transition. Also appears to require scripted cutscene to be interrupted** 
If you start Escoria directly into room 1 and immediately right click the first painting (during transition-in), all "look at" text (paintings 1 and 2) are now broken. If you go to room 2 then back to 1, look at now works. I assume this is a timing thing - I've tried to look at the painting before the dialogue plugin was registered?

* Note : Trying the same thing in room 5 doesn't have the same result (i.e. looking at the pipe or pen while transition in is happening)

I'm not sure if

**To Reproduce**
As above

**Expected behavior**
Not the above

**Screenshots**

**Versions**
* Escoria: Latest
* Godot: 3.4.4

**Additional context**

**Comment by BHSDuncan** [comment]
The `:ready` event is queued to run after `:transition_in` but `:transition_in` is being interrupted by that click which also cancels any queued events as well, i.e. `:ready` in this case.

And, in room 1, the `:ready` event includes some global var definitions that are used by the paintings to determine what is done, and without those global vars set, nothing happens. But when you come back in from another room (e.g. room 2), `:ready` is run that time.

We DO have a way to specify event exemptions as part of the interruption process (I've also found a small bug with the interruption code but it's easily fixed); however, interrupting in room 1 with such an exception during `:transition_in` will do the following:

1. Interrupt `:transition_in`, which will be allowed to complete.
2. As part of the interruption process, cancel any other running or queued events, except `:ready` which will remain in the event queue.
3. After `:transition_in` completes (as part of the interruption process), `:ready` will be popped from the queue and executed, and because the "look" action is an immediate action (as opposed to a queued event), it will be lost.

So this raises the question of how to handle clicks during a transition in.

I'd submit that we should disallow any and all user input during a transition in since I believe we already do something similar for transitions out.

Definitely open to discussion on this @balloonpopper and @StraToN .

**Comment by balloonpopper** [comment]
I would expect we should block during transition ins. My thought here is are we at risk of locking everything up if the transition gets stuck for unknown reasons and the player can't quit to fix it. I'm not sure if that's a valid concern.

**Comment by balloonpopper** [comment]
As per your comment above, we should also have a way to break out of cutscenes - with a "run after cutscene" code section perhaps to make sure that globals etc set during the cutscene set the game state how it's expected to be.

**Comment by BHSDuncan** [comment]
This would speak to interrupting cutscenes (or transitions) properly and I think this might have to be a post-4.0 release item.

**Comment by BHSDuncan** [comment]
As for blocking during a transition, I’d think we should probably disallow user input just as we do for transition out. Will wait for Julian’s feedback though.

**Comment by StraToN** [comment]
I agree, inputs should be disabled during transition (in or out). Skipping a transition is not supposed to happen - while skipping a cutscene is definitely desirable (but I agree that this will happen after 4.0)

**Comment by BHSDuncan** [comment]
We actually block input during `change_scene`, but only via that call and not for specific transitions. Will look at a way to address this.
