### ISSUE TITLE
Moving into a room where an exit has no global_id crashes

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#285]
**Describe the bug**
Room 12:
* Crash moving to room 13
The crash is in esc_object_manager.gd line 103 as object 8016 has no field "name". 8016 is escoria/main_scene/escoria_scene/main/room13/Hotspots/r_door
Checking "r_door" in room 13 it has no global_id. Giving this a global_id and testing room 12->13 transition again shows this fixed the problem. 

**To Reproduce**
As above

**Expected behavior**
Either the door with the missing global_id should be automatically assigned one, or the engine should crash gracefully and give an error message describing the room and object which is missing a global_id.

**Screenshots**

**Versions**
* Escoria: Latest
* Godot: 3.4.4

**Comment by BHSDuncan** [comment]
@balloonpopper are you sure this is an issue? I can't reproduce with the current `develop` branch. In fact, the code that we discussed the other day (re auto-assigning a global_id if one's missing) has been in the repo for months now).

Can you try again and if you can reproduce, let's discuss. Otherwise, please close the issue. Thanks!

**Comment by balloonpopper** [comment]
@BHSDuncan No idea why this was breaking the other day when I logged it. It's definitely working now so I'll close it.

WARNING: ESC (2022-07-17T12:17:47) W esc_object_manager.gd: Registering ESCObject r_door with empty global_id.Using node's full path as global_id: room13/Hotspots/r_door
