### ISSUE TITLE
Ending a text by " :" causes error message

### ISSUE THREAD

**Issue by polygoniaC-album** [godot-escoria/escoria-issues#326]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
In ESC Script, texts ending with ":" crash the game
Example :
`say player "blah blah blah :"`
causes :
`Arguments didn't match minimum size 2: Only 1 were found`

**To Reproduce**
As above

**Expected behavior**
No crash

**Screenshots**

**Versions**
* Escoria: Latest
* Godot: 3.5

**Additional context**
the error seems to come from line 49 of esc_command.gd :
`elif ':"' in parameter and (parameter.ends_with(':"') or not parameter.ends_with('"')):`
the code tries to open the quote when it is already open.

**Comment by BHSDuncan** [comment]
As discussed on Discord, this is likely because translation keys make use of colons and the parsing is treating the text as a key. We'll have to take a closer look.

Also, when reporting which version of Escoria you're using, if there's no version number, please refer to a commit hash as "Latest" could mean something very different tomorrow. Thanks.
