### ISSUE TITLE
Pause menu is not clickable while character is talking

### ISSUE THREAD

**Issue by StraToN** [godot-escoria/escoria-issues#352]
**Describe the bug**
Pause menu buttons can't be clicked while Mark is talking. Clicks are enabled only when Mark is finished talking.

**To Reproduce**

Start in room 1, 
go to room 2, 
go back to room 1 and walk to the middle of the room. 
The say command for the trigger area will be firing so Mark will be in the middle of saying something. 
Press ESC while he's talking, you can get back to the menu, but the buttons won't work until he finishes talking in the background.

**Expected behavior**
Pause menu buttons are usable at any time.

**Screenshots**
N/A

**Versions**
* Escoria: develop branch
* Godot: 3.5.1 stable

**Additional context**
N/A

**Comment by BHSDuncan** [comment]
This will require some discussion since the `say` command sets `escoria.current_state` to `GAME_STATE.DIALOG` which prevents the action manager from responding to clicks, etc. (there's a check at the top of `do` that says: `if escoria.current_state == escoria.GAME_STATE.DEFAULT:`).

One thing to go over is the expected behaviour of Escoria while in the `DIALOG` game state.

**Comment by StraToN** [comment]
To be tackled after the dialog encapsulation to dialog plugin task is done.
