### ISSUE TITLE
Fix Getted Started documentation to reflect current state of Escoria and let a dev get up to speed quickly

### ISSUE THREAD

**Issue by cidneyhamilton** [godot-escoria/escoria-issues#365]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
The Escoria documentation is confusingly out of date and following the instructions literally will not work. 

Should clarify:
- version number needed (Godot 4 will not work with Escoria; 3.5.2 is supported)
- Directions to create an Escoria project reference the Template Library version; which is years out of date. Should direct people to clone the relevant repositories instead. 
- Various typos and inconsistent references. These aren't blockers, but could easily be cleaned up.

**Comment by jnikula** [comment]
Sorry to pile on an old issue, but...

> version number needed (Godot 4 will not work with Escoria; 3.5.2 is supported)

I don't think this part was actually fixed by https://github.com/godot-escoria/escoria-docs/pull/71. Finding that information anywhere is still hard.

> Directions to create an Escoria project reference the Template Library version; which is years out of date. Should direct people to clone the relevant repositories instead.

This is probably me being a newbie with Godot/Escoria, but the text added in commit https://github.com/godot-escoria/escoria-docs/pull/71/commits/650e18b39adc08380c8e663a2f81513f37e9912e didn't actually help me. Especially "copy over the addons folder" is confusing. Over to where? I'm afraid I still don't know how I should start an Escoria project.
