### ISSUE TITLE
Loading/saving problems

### ISSUE THREAD

**Issue by dploeger** [godot-escoria/escoria-issues#73]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
* [x] Saving a game adds the object "player_start" which is not in the current room
* [x] Loading a game from the main menu doesn't hide the load screen
* [x] Loading a game from room01 while the initial walking animation event is running will wait until that event is run and not interrupted.
* [x] Saving a game containing objects with empty global_id is a problem. Use full node path instead if global_id is empty?

**Comment by StraToN** [comment]
> Saving a game adds the object "player_start" which is not in the current room

This was caused by these lines in ESCRoom: 
https://github.com/godot-escoria/escoria-demo-game/blob/09446c794f830abe149cb29656b47b8d56712505/addons/escoria-core/game/core-scripts/esc_room.gd#L113-L118

This parses the room nodes, searching for an ESCLocation that's also a start location, and register it in Escoria. However, ESCLocation already registers itself:
https://github.com/godot-escoria/escoria-demo-game/blob/09446c794f830abe149cb29656b47b8d56712505/addons/escoria-core/game/core-scripts/esc_location.gd#L32-L41

So simply removing these lines in ESCRoom will fix the issue.

**Comment by StraToN** [comment]
> Loading a game from the main menu doesn't hide the load screen

Not sure I can reproduce. This works in the work branch.

**Comment by StraToN** [comment]
> Loading a game from room01 while the initial walking animation event is running will wait until that event is run and not interrupted.

Fixed
